language: generic
env:
  global:
  - secure: Wmzcl21YO0Hsf0WvBTjVlJIpcy4LiigwMIQQNsT6qtzqJLK369pzsjnGfmmmM3/yI1pObum36xMmQUGgdmHj9uhnRDcPA0mivPt2Fez+1IKPqkXPZLyWNN7T2XE0GtU7mnjeerwbMtrOq4CxfZptVo/2HZcsIWVURI24bAmzaHy7JQKYoUQHVjVt3PNtkVV4sOfZHizISYWlaMMqDICLR179DstLsSbFiTdVn/8fLRcPYbiF62QgsyYqWKkZu8ySF8tM+j1du9hIW+6y0ogQuITDaZrJeYMOmnXNgOmr+GZCDxUb2HxoJQ5arsRR+gawSv9iXkPr0x9mRK4pPIKgFAZEqQSOOoKiPBKobkBzlpRjLMSZsVyEo0y1Bx/nhCHQdxPP7lq/H0Dm/GX+35y9CrjEUrlx2bn+LBgoZVkV8QUK/UnuVILjyQVMLubCOaPwkDN5unhom9WuSB7np/u2fAmrNJifAAeCex3T0yZ6GomWqZtQgBxB2IVMGGO6Ts1X4evYrwBmhF4T/9SIiYtLgpaLyA2kuFaiQuU8bbBTrsl8oI2fYiScF5XecfUe/7SOoPCL9O2RBwD/XTBXcij/1LNvJqVtefR6I48V7Q+qhfo1b342Oao97SQEnOr6S7pYywFCNKiUNhdNdyDuOy2I2oRRLz0phGOPqanSRYnWmGk=
script:
  - npm install --ignore-scripts
  - npm run docs:prepare
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _book
  on:
    branch: master
