language: generic
env:
  global:
    secure: hcTHrf5PZM355WjbcAjCbhNLS+6dOfqRsc6iR0fq6NHCdzDBqJja7spAJP9Qfth3Tt4TBr6NJ24GVX6T+97OlfQEJZKMipk0KC/ogS2VZoGyQdL7s2V6DIgD5/iC2MHrMNROJ5kmlEZwG1EtiWKd7WN+wHMMlmoP7Z9p6ZnfdMniLTz/DsUrkSr/gfhsBoutzfETzxCBbtpTe8dgIAG/4Eo73XaSKqQzKc/Sk6fXvCZXP2oKovUnqa9bYYE3pyBK7X7O7f96tdt0/WEhDzudux41yeG0GiIQ9hE3w6VDUvDxMEwB+JQpYzXjm1qyw+IrssTPHlRn9KLuzfMPeCsBlMY9DgNM8DFhQYCXjr0uiwP3t9QmuPlvA/9xqtat2wbHUP6/K1y1SJgQCpEAGS7YHQ0zIRLv6BYTRO3gtbELln9nhYC8OtpNno25f2rHSzg9+XYW1Ea2of0tTKRNtwE8yPDnW2Nz1m1ipH3+b+ECDroOOP0FVG5pxFa/QjfLjTNi8DwAhBFxGyp4aCNf5dsT1ua/8wzmA3TDZKrdvGVOV1IkdiNpzqet+vlLuh3RbxjTTB6zM5dFEjjfqmtJTo2MT2BjCRo5u/inzJwGGzZz+MidWQfNFwQ42DldoddN03PztQdpfOZczRiOxH5mMAi5tNkgxdW6FjYxgTc5dPTpJ/o=
script:
  - npm install --ignore-scripts
  - npm run docs:prepare
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: _book
  on:
    branch: master
